Add friends likes
Evgeny2835/java-filmorate pull request #2
Opened 2022-05-28 12:57 UTC by Evgeny2835

2022-05-28 20:14 UTC, kukolev requested changes

2022-05-28 20:14 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        System.out.println(e.getClass().getSimpleName());
Логирование необходимо делать с помощью предназначенных для этого средств: через создание Logger или аннотацию @Slf4j. Это лучше, т.к. тогда можно будет управлять логированием в настройках.

2022-05-28 20:14 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        String message = "Параметры должны принимать положительные значения";
Эту переменную лучше оформить как константу. Тогда эта строка не будет каждый раз создаваться при запуске метода.

2022-05-28 20:14 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        String message = String.format("Не существует пользователь с id=%d", userId);
Лучше использовать возможности библиотеки для логирования, чем конкатенацию строк: `log.info("Get user by id: {}", filmId)` вместо `log.info("Get user by id: " + filmId)`. Так тратится меньше ресурсов и код выглядит лучше.

2022-05-28 20:14 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        String message = String.format("Не существует фильм с id=%d", id);
Лучше использовать возможности библиотеки для логирования, чем конкатенацию строк: `log.info("Get user by id: {}", filmId)` вместо `log.info("Get user by id: " + filmId)`. Так тратится меньше ресурсов и код выглядит лучше.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        //filmController = new FilmController();
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +  /*  @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        //userController = new UserController();
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +  /*  @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +  /*  @Test
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-28 20:59 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        System.out.println(e.getClass().getSimpleName());
Строку удалил, ее наличие не предполагалось, не удалил по невнимательности.
При написании кода была ошибка, связанная с NPE в private Set<Long> likes класса Film.
Обозначенная строка добавлялась для "отлова" ошибки, не было очевидно, в чем проблема.

2022-05-28 21:08 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        String message = "Параметры должны принимать положительные значения";
Исправил.
Только среда разработки "докладывает", что "Field can be converted to a local variable", вероятно, из-за того, что в классе переменна используется один раз.

2022-05-29 09:12 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        String message = String.format("Не существует пользователь с id=%d", userId);
Замечание понял, после обсуждения в Slack, оставил пока текущий код, не корректировал.

2022-05-29 09:13 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        String message = String.format("Не существует фильм с id=%d", id);
Замечание понял, после обсуждения в Slack, оставил пока текущий код, не корректировал.

2022-05-29 09:20 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        //filmController = new FilmController();
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:21 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:21 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:21 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:21 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:22 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Исправил, тесты удалил, их присутствие не предполагалось, по невнимательности оставил от ТЗ-8.

2022-05-29 09:27 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:27 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Удалил.

2022-05-29 09:27 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:27 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +  /*  @Test
Удалил.

2022-05-29 09:27 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:28 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    /*@Test
Удалил.

2022-05-29 09:28 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        //userController = new UserController();
Удалил.

2022-05-29 09:28 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:29 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:29 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:29 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:29 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +   /* @Test
Удалил.

2022-05-29 09:30 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +  /*  @Test
Удалил.

2022-05-29 09:30 UTC, Evgeny2835 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +  /*  @Test
Удалил.

2022-05-29 22:26 UTC, kukolev requested changes
Наличие тестов как раз предполагалось. Тесты были сделаны в предыдущем спринте и тесты должны остаться. Нужно не удалять тесты, а чинить их.

2022-05-30 10:37 UTC, Evgeny2835 commented
Тесты починил.

2022-05-30 13:54 UTC, kukolev approved these changes

2022-05-30 15:17 UTC, merged