Add database
Evgeny2835/java-filmorate pull request #4
Opened 2022-06-28 19:02 UTC by Evgeny2835

Final task sprint 11, review 1

2022-06-30 07:44 UTC, kukolev requested changes

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        String sql = "SELECT * FROM GENRES";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        String sql = "SELECT * FROM MPA_RATING";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            String sql = "UPDATE FILMS SET name = ?, description = ?, releaseDate = ?," +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikesDbStorage.java
> +        String sql = "SELECT FILMS.FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID , " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT NAME FROM MPA_RATING WHERE MPA_ID = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            String sql = "UPDATE USERS SET email = ?, login = ?, name = ?, birthday = ?" +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendsDbStorage.java
> +            String sql = "INSERT INTO FRIENDSHIPS (user_id, friend_id, status) VALUES (?, ?, ?)";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-30 07:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
По моему здесь тоже можно создать список по умолчанию, т.к. не бывает фильмов без жанров. Тогда в коде можно будет убрать проверки на null.

2022-07-01 13:32 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        String sql = "SELECT * FROM GENRES";
Исправлено.

2022-07-01 13:33 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        String sql = "SELECT * FROM MPA_RATING";
Исправлено.

2022-07-01 14:04 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            String sql = "UPDATE FILMS SET name = ?, description = ?, releaseDate = ?," +
Исправлено

2022-07-01 14:18 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikesDbStorage.java
> +        String sql = "SELECT FILMS.FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID , " +
Исправлено.

2022-07-01 14:20 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT NAME FROM MPA_RATING WHERE MPA_ID = ?";
Исправлено.

2022-07-01 14:31 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            String sql = "UPDATE USERS SET email = ?, login = ?, name = ?, birthday = ?" +
Исправлено.

2022-07-01 14:40 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendsDbStorage.java
> +            String sql = "INSERT INTO FRIENDSHIPS (user_id, friend_id, status) VALUES (?, ?, ?)";
Исправлено.

2022-07-01 15:13 UTC, Evgeny2835 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Согласен, что фильмов без жанров не должно быть.
Но тесты требуют null.
В целом тесты отличные, но зачастую сложно разобраться, что требуется.

2022-07-01 16:40 UTC, kukolev approved these changes

2022-07-03 08:49 UTC, merged